# Generated by Django 6.0.3 on 2026-03-25 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome completo / Razão Social')),
                ('cpf_cnpj', models.CharField(max_length=14, unique=True, verbose_name='CPF / CNPJ')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_servico', models.TextField(verbose_name='Descrição do Serviço')),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Bruto (R$)')),
                ('valor_iss', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Valor ISS (R$)')),
                ('emitida_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Emissão')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='core.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Nota Fiscal',
                'verbose_name_plural': 'Notas Fiscais',
                'ordering': ['-emitida_em'],
            },
        ),
    ]
